name: Update sources data

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2
        with:
          version: 6.2.5

      - run: pnpm i
      - run: pnpm sources
        env:
          FLOCK_GITHUB_ACCESS_TOKEN: ${{ secrets.FLOCK_GITHUB_ACCESS_TOKEN }}
      - run: pnpm build

      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
